name: build

on:
  push:
    branches: [master]

jobs:
  style:
    name: style
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install pipenv
      - run: pipenv install --dev --system --deploy --ignore-pipfile
      - run: flake8 .
      - run: black --line-length 120 --check .
      - run: isort --check --line-length 120 --profile black .
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [style]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - run: echo "container_tag=$(date +'%FT%H%M%SZ')" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/binkhq/tagbot:${{ env.container_tag }}
            ghcr.io/binkhq/tagbot:latest
